In [6]:
!pip install torch torchvision


     |████████████████████████████████| 436 kB 425 kB/s eta 0:00:01
     |████████████████████████████████| 2.2 MB 1.0 MB/s eta 0:00:01     |███████████████████████         | 1.6 MB 1.0 MB/s eta 0:00:01
  Attempting uninstall: pillow
    Found existing installation: Pillow 3.1.1
    Uninstalling Pillow-3.1.1:
      Successfully uninstalled Pillow-3.1.1


In [7]:
from __future__ import print_function

import torch

In [9]:
x= torch.rand(5,3)
print(x)

tensor([[0.7494, 0.5189, 0.0894],
        [0.3939, 0.0673, 0.9713],
        [0.0925, 0.1196, 0.6310],
        [0.9940, 0.7542, 0.2136],
        [0.2256, 0.9869, 0.9843]])


In [11]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [12]:
x= torch.tensor([5.5,3])

In [19]:
#x= torch.tensor([5.5,3])
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [21]:
x = torch.randn_like(x, dtype= torch.float)
print(x)

tensor([[-0.0912, -1.9012,  0.4071],
        [ 1.0639, -0.4482, -0.9005],
        [-0.2238, -0.1243,  1.0268],
        [ 0.1535,  0.1139,  0.9352],
        [-0.2850, -0.4185, -0.2869]])


In [22]:
x=torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.7196,  0.3130,  0.3995],
        [-0.4741, -0.4139,  0.7095],
        [ 2.1364, -0.5777,  0.8803],
        [ 1.1299,  0.0930,  2.0348],
        [ 0.6173,  0.2184,  0.2107]])


In [23]:
print(x.size())

torch.Size([5, 3])


In [24]:
y = torch.rand(5,3)

In [25]:
print(x+y)

tensor([[ 1.7645,  0.3557,  0.9783],
        [-0.0194,  0.1498,  0.9489],
        [ 2.3127, -0.3001,  1.0183],
        [ 1.1670,  0.4703,  2.3240],
        [ 1.5512,  1.0370,  1.1988]])


In [26]:
print(torch.add(x,y))

tensor([[ 1.7645,  0.3557,  0.9783],
        [-0.0194,  0.1498,  0.9489],
        [ 2.3127, -0.3001,  1.0183],
        [ 1.1670,  0.4703,  2.3240],
        [ 1.5512,  1.0370,  1.1988]])


In [27]:
a = torch.ones(5)

In [28]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [29]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [30]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [32]:
import numpy as np

a= np.ones(5)

In [34]:
print(a)
print(b)

[ 1.  1.  1.  1.  1.]
[ 2.  2.  2.  2.  2.]
